title: "hanzo's blog"
description: "newb ctf player | rev & pwn enthusiast"
url: "https://rayhanhanaputra.github.io" 
baseurl: ""
markdown: kramdown
show_excerpts: true
excerpt_separator: "<!--more-->"
theme: jekyll-theme-hacker
author: hanzo

# Disable GitHub button in hacker theme
github:
  is_project_page: false

plugins: []

exclude:
  - README.md
