title: "hanzo's blog"
description: "my ctf writeups"
url: "https://hanz0x17.github.io" 
baseurl: ""
markdown: kramdown
show_excerpts: true
theme: minima
author: hanzo

github_username: hanz0x17
twitter_username: hanz0x17
discord_username: hanz0x17

plugins: []

exclude:
  - README.md
